version = 1

[build]
towebp.command = '''
mkdir -p $out/bin
cp towebp.py $out/bin/towebp.py
'''

[install]
python3 = { pkg-path = "python312" }
click = { pkg-path = "python312Packages.click" }
pillow = { pkg-path = "python312Packages.pillow" }

[hook]
on-activate = '''
'''

[profile]
bash = '''
  source "$PYTHON_DIR/bin/activate"
'''
fish = '''
  source "$PYTHON_DIR/bin/activate.fish"
'''
tcsh = '''
  source "$PYTHON_DIR/bin/activate.csh"
'''
zsh = '''
  source "$PYTHON_DIR/bin/activate"
'''

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
