version = 1

[install]
python3 = { pkg-path = "python3" }

[hook]
on-activate = '''
  export PYTHON_DIR="$FLOX_ENV_CACHE/python"
  if [ ! -d "$PYTHON_DIR" ]; then
    echo "Creating python virtual environment in $PYTHON_DIR"
    python -m venv "$PYTHON_DIR"
  fi

  (
    source "$PYTHON_DIR/bin/activate"
    pip install -r "$FLOX_ENV_PROJECT/requirements.txt" --quiet
  )
'''

[profile]
bash = '''
  source "$PYTHON_DIR/bin/activate"
'''
fish = '''
  source "$PYTHON_DIR/bin/activate.fish"
'''
tcsh = '''
  source "$PYTHON_DIR/bin/activate.csh"
'''
zsh = '''
  source "$PYTHON_DIR/bin/activate"
'''

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
