version = 1

[build]
towebp.command = '''
mkdir -p $out/bin
cp towebp.py $out/bin/towebp
'''

[install]
python3 = { pkg-path = "python312" }
click = { pkg-path = "python312Packages.click" }
pillow = { pkg-path = "python312Packages.pillow" }

